FROM tomcat:9.0-jdk17-openjdk-slim
# Remove default Tomcat apps to keep it clean
RUN rm -rf /usr/local/tomcat/webapps/*
# Copy the WAR file generated by Maven into Tomcat
COPY target/*.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
CMD ["catalina.sh", "run"]
